//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psycho.Laborer.Repo.Script {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Psycho.Laborer.Repo.Script.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE TABLE &quot;Occupation&quot; (
        ///	&quot;Id&quot; REAL NOT NULL CONSTRAINT &quot;PK_Occupation&quot; PRIMARY KEY,
        ///	&quot;OccupationType&quot; INTEGER,
        ///	&quot;Occupationname&quot; TEXT, 
        ///);
        ///
        ///CREATE TABLE &quot;City&quot; (
        ///	&quot;Id&quot; INTEGER NOT NULL CONSTRAINT &quot;PK_City&quot; PRIMARY KEY,
        ///	&quot;Name&quot; TEXT
        ///);
        ///
        ///CREATE TABLE &quot;Country&quot; (
        ///	&quot;Id&quot; INTEGER NOT NULL CONSTRAINT &quot;PK_Country&quot; PRIMARY KEY,
        ///	&quot;Name&quot; TEXT 
        ///);
        ///
        ///CREATE TABLE &quot;Career&quot; (
        ///	&quot;Id&quot; INTEGER NOT NULL CONSTRAINT &quot;PK_Career&quot; PRIMARY KEY AUTOINCREMENT,
        ///	&quot;UserGetId&quot; INTEGER NOT NULL,
        ///	&quot;GroupId&quot; INTEGER NOT [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CreateDb {
            get {
                return ResourceManager.GetString("CreateDb", resourceCulture);
            }
        }
    }
}
